package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

/**
 * HafuUserProfileComment generated by hbm2java
 */
public class HafuUserProfileComment implements java.io.Serializable {

	private Integer pid;
	private HafuUserComment hafuUserComment;
	private String name;
	private Integer gender;
	private String userAddress;
	private String phone;

	public HafuUserProfileComment() {
	}

	public HafuUserProfileComment(HafuUserComment hafuUserComment, String name, Integer gender, String userAddress,
			String phone) {
		this.hafuUserComment = hafuUserComment;
		this.name = name;
		this.gender = gender;
		this.userAddress = userAddress;
		this.phone = phone;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public HafuUserComment getHafuUserComment() {
		return this.hafuUserComment;
	}

	public void setHafuUserComment(HafuUserComment hafuUserComment) {
		this.hafuUserComment = hafuUserComment;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
