package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HafuUserComment generated by hbm2java
 */
public class HafuUserComment implements java.io.Serializable {

	private Integer uid;
	private String username;
	private String password;
	private Date regtime;
	private Set hafuUserProfileComments = new HashSet(0);

	public HafuUserComment() {
	}

	public HafuUserComment(Date regtime) {
		this.regtime = regtime;
	}

	public HafuUserComment(String username, String password, Date regtime, Set hafuUserProfileComments) {
		this.username = username;
		this.password = password;
		this.regtime = regtime;
		this.hafuUserProfileComments = hafuUserProfileComments;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public Set getHafuUserProfileComments() {
		return this.hafuUserProfileComments;
	}

	public void setHafuUserProfileComments(Set hafuUserProfileComments) {
		this.hafuUserProfileComments = hafuUserProfileComments;
	}

}
