package com.hafu.domain;
// Generated 2017-7-25 11:03:09 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * HafuCheckoutComment generated by hbm2java
 */
public class HafuCheckoutComment implements java.io.Serializable {

	private Integer cid;
	private int uid;
	private Set hafuCheckoutGoodComments = new HashSet(0);

	public HafuCheckoutComment() {
	}

	public HafuCheckoutComment(int uid) {
		this.uid = uid;
	}

	public HafuCheckoutComment(int uid, Set hafuCheckoutGoodComments) {
		this.uid = uid;
		this.hafuCheckoutGoodComments = hafuCheckoutGoodComments;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public Set getHafuCheckoutGoodComments() {
		return this.hafuCheckoutGoodComments;
	}

	public void setHafuCheckoutGoodComments(Set hafuCheckoutGoodComments) {
		this.hafuCheckoutGoodComments = hafuCheckoutGoodComments;
	}

}
