package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HafuStoreComment generated by hbm2java
 */
public class HafuStoreComment implements java.io.Serializable {

	private Integer sid;
	private String storename;
	private String storeAddress;
	private String storeProfile;
	private Integer type;
	private Integer status;
	private String icon;
	private Double fee;
	private Double deliveryRange;
	private Date openingTime;
	private Set hafuGoodComments = new HashSet(0);

	public HafuStoreComment() {
	}

	public HafuStoreComment(String storename, String storeAddress, String storeProfile, Integer type, Integer status,
			String icon, Double fee, Double deliveryRange, Date openingTime, Set hafuGoodComments) {
		this.storename = storename;
		this.storeAddress = storeAddress;
		this.storeProfile = storeProfile;
		this.type = type;
		this.status = status;
		this.icon = icon;
		this.fee = fee;
		this.deliveryRange = deliveryRange;
		this.openingTime = openingTime;
		this.hafuGoodComments = hafuGoodComments;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getStorename() {
		return this.storename;
	}

	public void setStorename(String storename) {
		this.storename = storename;
	}

	public String getStoreAddress() {
		return this.storeAddress;
	}

	public void setStoreAddress(String storeAddress) {
		this.storeAddress = storeAddress;
	}

	public String getStoreProfile() {
		return this.storeProfile;
	}

	public void setStoreProfile(String storeProfile) {
		this.storeProfile = storeProfile;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Double getFee() {
		return this.fee;
	}

	public void setFee(Double fee) {
		this.fee = fee;
	}

	public Double getDeliveryRange() {
		return this.deliveryRange;
	}

	public void setDeliveryRange(Double deliveryRange) {
		this.deliveryRange = deliveryRange;
	}

	public Date getOpeningTime() {
		return this.openingTime;
	}

	public void setOpeningTime(Date openingTime) {
		this.openingTime = openingTime;
	}

	public Set getHafuGoodComments() {
		return this.hafuGoodComments;
	}

	public void setHafuGoodComments(Set hafuGoodComments) {
		this.hafuGoodComments = hafuGoodComments;
	}

}
