package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

/**
 * HafuOrderGoodCommentId generated by hbm2java
 */
public class HafuOrderGoodCommentId implements java.io.Serializable {

	private int orderid;
	private int gid;

	public HafuOrderGoodCommentId() {
	}

	public HafuOrderGoodCommentId(int orderid, int gid) {
		this.orderid = orderid;
		this.gid = gid;
	}

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HafuOrderGoodCommentId))
			return false;
		HafuOrderGoodCommentId castOther = (HafuOrderGoodCommentId) other;

		return (this.getOrderid() == castOther.getOrderid()) && (this.getGid() == castOther.getGid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrderid();
		result = 37 * result + this.getGid();
		return result;
	}

}
