package com.hafu.domain;
// Generated 2017-7-25 11:03:09 by Hibernate Tools 5.2.3.Final

/**
 * HafuCheckoutGoodCommentId generated by hbm2java
 */
public class HafuCheckoutGoodCommentId implements java.io.Serializable {

	private int cid;
	private int gid;

	public HafuCheckoutGoodCommentId() {
	}

	public HafuCheckoutGoodCommentId(int cid, int gid) {
		this.cid = cid;
		this.gid = gid;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public int getGid() {
		return this.gid;
	}

	public void setGid(int gid) {
		this.gid = gid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HafuCheckoutGoodCommentId))
			return false;
		HafuCheckoutGoodCommentId castOther = (HafuCheckoutGoodCommentId) other;

		return (this.getCid() == castOther.getCid()) && (this.getGid() == castOther.getGid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCid();
		result = 37 * result + this.getGid();
		return result;
	}

}
