package com.hafu.domain;
// Generated 2017-7-25 11:03:09 by Hibernate Tools 5.2.3.Final

/**
 * HafuCheckoutGoodComment generated by hbm2java
 */
public class HafuCheckoutGoodComment implements java.io.Serializable {

	private HafuCheckoutGoodCommentId id;
	private HafuCheckoutComment hafuCheckoutComment;
	private int goodnumber;

	public HafuCheckoutGoodComment() {
	}

	public HafuCheckoutGoodComment(HafuCheckoutGoodCommentId id, HafuCheckoutComment hafuCheckoutComment,
			int goodnumber) {
		this.id = id;
		this.hafuCheckoutComment = hafuCheckoutComment;
		this.goodnumber = goodnumber;
	}

	public HafuCheckoutGoodCommentId getId() {
		return this.id;
	}

	public void setId(HafuCheckoutGoodCommentId id) {
		this.id = id;
	}

	public HafuCheckoutComment getHafuCheckoutComment() {
		return this.hafuCheckoutComment;
	}

	public void setHafuCheckoutComment(HafuCheckoutComment hafuCheckoutComment) {
		this.hafuCheckoutComment = hafuCheckoutComment;
	}

	public int getGoodnumber() {
		return this.goodnumber;
	}

	public void setGoodnumber(int goodnumber) {
		this.goodnumber = goodnumber;
	}

}
