package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

/**
 * HafuOrderGoodComment generated by hbm2java
 */
public class HafuOrderGoodComment implements java.io.Serializable {

	private HafuOrderGoodCommentId id;
	private HafuGoodComment hafuGoodComment;
	private HafuOrderComment hafuOrderComment;
	private Integer goodnumber;

	public HafuOrderGoodComment() {
	}

	public HafuOrderGoodComment(HafuOrderGoodCommentId id, HafuGoodComment hafuGoodComment,
			HafuOrderComment hafuOrderComment) {
		this.id = id;
		this.hafuGoodComment = hafuGoodComment;
		this.hafuOrderComment = hafuOrderComment;
	}

	public HafuOrderGoodComment(HafuOrderGoodCommentId id, HafuGoodComment hafuGoodComment,
			HafuOrderComment hafuOrderComment, Integer goodnumber) {
		this.id = id;
		this.hafuGoodComment = hafuGoodComment;
		this.hafuOrderComment = hafuOrderComment;
		this.goodnumber = goodnumber;
	}

	public HafuOrderGoodCommentId getId() {
		return this.id;
	}

	public void setId(HafuOrderGoodCommentId id) {
		this.id = id;
	}

	public HafuGoodComment getHafuGoodComment() {
		return this.hafuGoodComment;
	}

	public void setHafuGoodComment(HafuGoodComment hafuGoodComment) {
		this.hafuGoodComment = hafuGoodComment;
	}

	public HafuOrderComment getHafuOrderComment() {
		return this.hafuOrderComment;
	}

	public void setHafuOrderComment(HafuOrderComment hafuOrderComment) {
		this.hafuOrderComment = hafuOrderComment;
	}

	public Integer getGoodnumber() {
		return this.goodnumber;
	}

	public void setGoodnumber(Integer goodnumber) {
		this.goodnumber = goodnumber;
	}

}
