package com.hafu.domain;
// Generated 2017-7-21 16:02:03 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * HafuGoodComment generated by hbm2java
 */
public class HafuGoodComment implements java.io.Serializable {

	private Integer gid;
	private HafuStoreComment hafuStoreComment;
	private String goodname;
	private Double goodPrice;
	private String icon;
	private String goodProfile;
	private Integer goodStatus;
	private Set hafuOrderComments = new HashSet(0);
	private Set hafuOrderGoodComments = new HashSet(0);

	public HafuGoodComment() {
	}

	public HafuGoodComment(HafuStoreComment hafuStoreComment, String goodname, Double goodPrice, String icon,
			String goodProfile, Integer goodStatus, Set hafuOrderComments, Set hafuOrderGoodComments) {
		this.hafuStoreComment = hafuStoreComment;
		this.goodname = goodname;
		this.goodPrice = goodPrice;
		this.icon = icon;
		this.goodProfile = goodProfile;
		this.goodStatus = goodStatus;
		this.hafuOrderComments = hafuOrderComments;
		this.hafuOrderGoodComments = hafuOrderGoodComments;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public HafuStoreComment getHafuStoreComment() {
		return this.hafuStoreComment;
	}

	public void setHafuStoreComment(HafuStoreComment hafuStoreComment) {
		this.hafuStoreComment = hafuStoreComment;
	}

	public String getGoodname() {
		return this.goodname;
	}

	public void setGoodname(String goodname) {
		this.goodname = goodname;
	}

	public Double getGoodPrice() {
		return this.goodPrice;
	}

	public void setGoodPrice(Double goodPrice) {
		this.goodPrice = goodPrice;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public String getGoodProfile() {
		return this.goodProfile;
	}

	public void setGoodProfile(String goodProfile) {
		this.goodProfile = goodProfile;
	}

	public Integer getGoodStatus() {
		return this.goodStatus;
	}

	public void setGoodStatus(Integer goodStatus) {
		this.goodStatus = goodStatus;
	}

	public Set getHafuOrderComments() {
		return this.hafuOrderComments;
	}

	public void setHafuOrderComments(Set hafuOrderComments) {
		this.hafuOrderComments = hafuOrderComments;
	}

	public Set getHafuOrderGoodComments() {
		return this.hafuOrderGoodComments;
	}

	public void setHafuOrderGoodComments(Set hafuOrderGoodComments) {
		this.hafuOrderGoodComments = hafuOrderGoodComments;
	}

}
