package com.hafu.domain;
// Generated 2017-8-10 10:33:21 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * HafuCheckoutComment generated by hbm2java
 */
public class HafuCheckoutComment implements java.io.Serializable {

	private Integer cid;
	private HafuUserComment hafuUserComment;
	private Set hafuCheckoutGoodComments = new HashSet(0);

	public HafuCheckoutComment() {
	}

	public HafuCheckoutComment(HafuUserComment hafuUserComment) {
		this.hafuUserComment = hafuUserComment;
	}

	public HafuCheckoutComment(HafuUserComment hafuUserComment, Set hafuCheckoutGoodComments) {
		this.hafuUserComment = hafuUserComment;
		this.hafuCheckoutGoodComments = hafuCheckoutGoodComments;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public HafuUserComment getHafuUserComment() {
		return this.hafuUserComment;
	}

	public void setHafuUserComment(HafuUserComment hafuUserComment) {
		this.hafuUserComment = hafuUserComment;
	}

	public Set getHafuCheckoutGoodComments() {
		return this.hafuCheckoutGoodComments;
	}

	public void setHafuCheckoutGoodComments(Set hafuCheckoutGoodComments) {
		this.hafuCheckoutGoodComments = hafuCheckoutGoodComments;
	}

}
